<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form action="/login" method="post">
    <input type="text" name="email" placeholder="Email" autocomplete="off"> <br><br>
    <input type="password" name="password" placeholder="Password"> <br><br>
    <input type="submit" class="send" value="Login">
</form> <br>
<a href="/signup">Sign Up</a>
</body>
</html>